# What is convolution?

In dumb way of saying is, convolution is just adding and multiplying

With convolution, there are three objects you need to pay attentin to.

1. Input Image
2. Filter (Kernel)
3. Output Image

Input Image * Filter = Output Image

Convolution = Image Modifier
** Feature Transformation on input image

Input Length = N
Kernel Length = K
Output Length = N-K+1


In [18]:
# code for applying filter
import numpy as np

N = np.array([[0,10,10,0],[20,30,30,20],[10,20,20,10],[0,5,5,0]])
K = np.array([[1,0],[0,2]])
 
output_height = 3
output_width = 3
output = np.zeros((output_height,output_width))

for i in range(output_height):
  for j in range(output_width):
    output[i][j] = np.sum((N[i:2+i,j:2+j]*K).flatten())

print(output)

[[60. 70. 50.]
 [60. 70. 50.]
 [20. 30. 20.]]


In [26]:
 # use convolution using scipy

from scipy.signal import convolve2d

convolve2d(N,np.fliplr(np.flipud(K)),mode='valid') 

array([[60, 70, 50],
       [60, 70, 50],
       [20, 30, 20]])

## Convolution as Pattern Finding

cos angle represents how similar a and b are

high positive co relation -> dot product is large and positive

high negative co relation -> dot product is large and negative

orthogonal -> dot product is zero

# CNN Architecture

A typical CNN has 2 stages

1. Series of convolution layers ( feature transformation )
2. Dense Layers ( FeedForward NN )

Pooling -> Downsizing your image

Max Pooling -> Extracting max value from each square 
Average Pooling -> Taking Average of 4 Values

Why we do pooling?

1. Practical
2. Transitional invarience

Why convolution followed by pooling

As the image shrinks and filter size stays the same, they find increasingly large patterns 

Hyper parameter Guideline :

1. Small filter size
2. Convolution -> Pooling -> Convo -> Pool follow this pattern
3. Increase number of feature maps